export const ALL_PRODUCTS = [
  {
    "id": "prod-0",
    "name": "Aamchur Powder",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 104,
    "spice": 3,
    "badge": "Bestseller",
    "badgeClass": "badge-bestseller",
    "emoji": "🏺",
    "img": "/images/products/aamchur-powder.jpg",
    "desc": "Premium Aamchur Powder. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-1",
    "name": "All Powder",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 422,
    "spice": 4,
    "badge": "Bestseller",
    "badgeClass": "badge-bestseller",
    "emoji": "🏺",
    "img": "/images/products/all-powder.jpg",
    "desc": "Premium All Powder. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-2",
    "name": "All Snacks",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 125,
    "spice": 4,
    "badge": "Bestseller",
    "badgeClass": "badge-bestseller",
    "emoji": "🏺",
    "img": "/images/products/all-snacks.jpg",
    "desc": "Premium All Snacks. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-3",
    "name": "Allam Avakaya",
    "category": "Prepared Foods",
    "rating": 5,
    "reviews": 227,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/allam-avakaya.jpg",
    "desc": "Premium Allam Avakaya. Authentic, traditional sun-dried pickle made with carefully selected ingredients and aromatic cold-pressed oils. Perfect companion for your meals."
  },
  {
    "id": "prod-4",
    "name": "Allam Velluli Karam",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 538,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/allam-velluli-karam.jpg",
    "desc": "Premium Allam Velluli Karam. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-5",
    "name": "Allam Velluli Pickle",
    "category": "Prepared Foods",
    "rating": 5,
    "reviews": 415,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Allam_Velluli_Pickle_(ginger_garlic_pickle).jpeg",
    "desc": "Premium Allam Velluli Pickle. Authentic, traditional sun-dried pickle made with carefully selected ingredients and aromatic cold-pressed oils. Perfect companion for your meals."
  },
  {
    "id": "prod-6",
    "name": "Allam Velluli Karam Podi",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 260,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Allam_Velluli_Karam_Podi_(ginger_garlic_spice_powder).jpeg",
    "desc": "Premium Allam Velluli Karam Podi. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-7",
    "name": "Allu Chips",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 268,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Allu_Chips_(thinly_sliced_Indian_potato_chips).jpeg",
    "desc": "Premium Allu Chips. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-8",
    "name": "Bellam Avakaya",
    "category": "Prepared Foods",
    "rating": 5,
    "reviews": 423,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Bellam_Avakaya_(sweet_jaggery_mango_pickle).jpeg",
    "desc": "Premium Bellam Avakaya. Authentic, traditional sun-dried pickle made with carefully selected ingredients and aromatic cold-pressed oils. Perfect companion for your meals."
  },
  {
    "id": "prod-9",
    "name": "Biryani Masala",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 265,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/biryani-masala.jpg",
    "desc": "Premium Biryani Masala. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-10",
    "name": "Bundhi",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 208,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Bundhi_(crispy_spiced_gram_flour_droplets).jpeg",
    "desc": "Premium Bundhi. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-11",
    "name": "Chakinalu",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 361,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Chakinalu_(traditional_Sankranti_spiral_snacks).jpeg",
    "desc": "Premium Chakinalu. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-12",
    "name": "Chakodi",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 138,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/chakodi.jpg",
    "desc": "Premium Chakodi. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-13",
    "name": "Chicken Masala",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 155,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/chicken-masala.jpg",
    "desc": "Premium Chicken Masala. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-14",
    "name": "Chicken Masala Powder",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 492,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Chicken_Masala_Powder_(chicken_curry_spice_blend).jpeg",
    "desc": "Premium Chicken Masala Powder. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-15",
    "name": "Daniya Powder",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 241,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Daniya_Powder_(freshly_ground_coriander_powder).jpeg",
    "desc": "Premium Daniya Powder. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-16",
    "name": "Dry Fruits Laddu",
    "category": "Indian Sweets & Snacks",
    "rating": 5,
    "reviews": 357,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Dry_Fruits_Laddu_(premium_dry_fruits_laddu).jpeg",
    "desc": "Premium Dry Fruits Laddu. Traditional, rich and wholesome sweet treat made with premium ingredients. A delightful experience for your sweet cravings."
  },
  {
    "id": "prod-17",
    "name": "Garam Masala",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 575,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/garam-masala.jpg",
    "desc": "Premium Garam Masala. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-18",
    "name": "Garam Masala Powder",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 188,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Garam_Masala_Powder_(traditional_warm_spice_blend).jpeg",
    "desc": "Premium Garam Masala Powder. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-19",
    "name": "Gondh Laddu",
    "category": "Indian Sweets & Snacks",
    "rating": 5,
    "reviews": 312,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Gondh_Laddu_(edible_gum_laddu).jpeg",
    "desc": "Premium Gondh Laddu. Traditional, rich and wholesome sweet treat made with premium ingredients. A delightful experience for your sweet cravings."
  },
  {
    "id": "prod-20",
    "name": "Haldi Powder",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 516,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Haldi_Powder_(pure_turmeric_powder).jpeg",
    "desc": "Premium Haldi Powder. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-21",
    "name": "Karam Janthukalu",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 559,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Karam_Janthukalu_(murukku_strings_snack).jpeg",
    "desc": "Premium Karam Janthukalu. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-22",
    "name": "Karvepaku Karam",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 265,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/karvepaku-karam.jpg",
    "desc": "Premium Karvepaku Karam. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-23",
    "name": "Karvepaku Karam Podi",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 251,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Karvepaku_Karam_Podi_(curry_leaves_powder).jpeg",
    "desc": "Premium Karvepaku Karam Podi. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-24",
    "name": "Khara Mixture",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 296,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Khara_Mixture_(assorted_crunchy_savory_mix).jpeg",
    "desc": "Premium Khara Mixture. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-25",
    "name": "Kova Gulam Jamun",
    "category": "Indian Sweets & Snacks",
    "rating": 5,
    "reviews": 292,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Kova_Gulam_Jamun_(rich_gulab_jamun_sweet).jpeg",
    "desc": "Premium Kova Gulam Jamun. Traditional, rich and wholesome sweet treat made with premium ingredients. A delightful experience for your sweet cravings."
  },
  {
    "id": "prod-26",
    "name": "Makha Chips",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 383,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/makha-chips.jpg",
    "desc": "Premium Makha Chips. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-27",
    "name": "Mango Pickle",
    "category": "Prepared Foods",
    "rating": 5,
    "reviews": 502,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/mango-pickle.jpg",
    "desc": "Premium Mango Pickle. Authentic, traditional sun-dried pickle made with carefully selected ingredients and aromatic cold-pressed oils. Perfect companion for your meals."
  },
  {
    "id": "prod-28",
    "name": "Masala Murmura",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 442,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/masala-murmura.jpg",
    "desc": "Premium Masala Murmura. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-29",
    "name": "Menthi Podi",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 150,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Menthi_Podi_(fenugreek_powder).jpeg",
    "desc": "Premium Menthi Podi. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-30",
    "name": "Millets Laddu",
    "category": "Indian Sweets & Snacks",
    "rating": 5,
    "reviews": 236,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Millets_Laddu_(wholesome_multi-millet_laddu).jpeg",
    "desc": "Premium Millets Laddu. Traditional, rich and wholesome sweet treat made with premium ingredients. A delightful experience for your sweet cravings."
  },
  {
    "id": "prod-31",
    "name": "Mirchi Powder",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 481,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/mirchi-powder.jpg",
    "desc": "Premium Mirchi Powder. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-32",
    "name": "Munagaku Karam",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 184,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/munagaku-karam.jpg",
    "desc": "Premium Munagaku Karam. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-33",
    "name": "Munagaku Powder",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 517,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/munagaku-powder.jpg",
    "desc": "Premium Munagaku Powder. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-34",
    "name": "Munagaku Karam Podi",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 205,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Munagaku_Karam_Podi_(moringa_leaves_spice_powder.jpeg",
    "desc": "Premium Munagaku Karam Podi. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-35",
    "name": "Muthyala Chudwa",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 410,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/muthyala-chudwa.jpg",
    "desc": "Premium Muthyala Chudwa. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-36",
    "name": "Mutton Masala",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 413,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/mutton-masala.jpg",
    "desc": "Premium Mutton Masala. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-37",
    "name": "Mutton Masala Powder",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 189,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Mutton_Masala_Powder_(mutton_recipe_spice_blend).jpeg",
    "desc": "Premium Mutton Masala Powder. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-38",
    "name": "Nuvvula Papad",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 263,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Nuvvula_Papad_(sesame_coated_crispy_papads).jpeg",
    "desc": "Premium Nuvvula Papad. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-39",
    "name": "Onion Whills",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 536,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Onion_Whills_(onion_flavored_crisp_wheels).jpeg",
    "desc": "Premium Onion Whills. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-40",
    "name": "Palli Patti",
    "category": "Indian Sweets & Snacks",
    "rating": 5,
    "reviews": 465,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Palli_Patti_(peanut_and_jaggery_chikki).jpeg",
    "desc": "Premium Palli Patti. Traditional, rich and wholesome sweet treat made with premium ingredients. A delightful experience for your sweet cravings."
  },
  {
    "id": "prod-41",
    "name": "Pandu Mirchi",
    "category": "Prepared Foods",
    "rating": 5,
    "reviews": 356,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/pandu-mirchi.jpg",
    "desc": "Premium Pandu Mirchi. Premium quality traditional Andhra delicacy made with authentic ingredients and time-honored recipes."
  },
  {
    "id": "prod-42",
    "name": "Putnala Karam",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 143,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/putnala-karam.jpg",
    "desc": "Premium Putnala Karam. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-43",
    "name": "Putnala Karam Podi",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 266,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Putnala_Karam_Podi_(roasted_gram_spice_powder).jpeg",
    "desc": "Premium Putnala Karam Podi. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-44",
    "name": "Rice Papad",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 443,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Rice_Papad_(crispy_rice_flour_papadums).jpeg",
    "desc": "Premium Rice Papad. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-45",
    "name": "Sambhar Masala",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 555,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/sambhar-masala.jpg",
    "desc": "Premium Sambhar Masala. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-46",
    "name": "Sambhar Masala Powder",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 413,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Sambhar_Masala_Powder_(authentic_sambhar_spice_blend).jpeg",
    "desc": "Premium Sambhar Masala Powder. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-47",
    "name": "Special Idli Karam",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 598,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/special-idli-karam.jpg",
    "desc": "Premium Special Idli Karam. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-48",
    "name": "Special Kura Karam",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 310,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/special-kura-karam.jpg",
    "desc": "Premium Special Kura Karam. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-49",
    "name": "Special Idli Karam Podi",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 135,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Special_Idli_Karam_Podi_(gun_powder_spice_for_idlis).jpeg",
    "desc": "Premium Special Idli Karam Podi. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-50",
    "name": "Special Kura Karam Podi",
    "category": "Salts, spices, soups",
    "rating": 5,
    "reviews": 376,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Special_Kura_Karam_Podi_(all-purpose_curry_powder).jpeg",
    "desc": "Premium Special Kura Karam Podi. Freshly ground, aromatic spice blend prepared using traditional stone-grinding methods. Adds rich flavor and authentic taste to your dishes."
  },
  {
    "id": "prod-51",
    "name": "Sunnunda Laddu",
    "category": "Indian Sweets & Snacks",
    "rating": 5,
    "reviews": 379,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Sunnunda_Laddu_(roasted_urad_dal_laddu).jpeg",
    "desc": "Premium Sunnunda Laddu. Traditional, rich and wholesome sweet treat made with premium ingredients. A delightful experience for your sweet cravings."
  },
  {
    "id": "prod-52",
    "name": "Sweet Chekki",
    "category": "Indian Sweets & Snacks",
    "rating": 5,
    "reviews": 269,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Sweet_Chekki_(traditional_sweet_brittle).jpeg",
    "desc": "Premium Sweet Chekki. Traditional, rich and wholesome sweet treat made with premium ingredients. A delightful experience for your sweet cravings."
  },
  {
    "id": "prod-53",
    "name": "Thill Patti",
    "category": "Indian Sweets & Snacks",
    "rating": 5,
    "reviews": 333,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Thill_Patti_(sesame_seed_and_jaggery_sweet).jpeg",
    "desc": "Premium Thill Patti. Traditional, rich and wholesome sweet treat made with premium ingredients. A delightful experience for your sweet cravings."
  },
  {
    "id": "prod-54",
    "name": "Tomato Chilli Papad",
    "category": "Ready-to-eat savouries",
    "rating": 5,
    "reviews": 542,
    "spice": 3,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Tomato_Chilli_Papad_(tangy_and_spicy_papads).jpeg",
    "desc": "Premium Tomato Chilli Papad. Crispy, savory traditional snack perfectly seasoned for a delightful crunch. The ultimate tea-time companion."
  },
  {
    "id": "prod-55",
    "name": "Uppava",
    "category": "Prepared Foods",
    "rating": 5,
    "reviews": 516,
    "spice": 2,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Uppava_(traditional_salted_pickle).jpeg",
    "desc": "Premium Uppava. Authentic, traditional sun-dried pickle made with carefully selected ingredients and aromatic cold-pressed oils. Perfect companion for your meals."
  },
  {
    "id": "prod-56",
    "name": "Usiri Pickle",
    "category": "Prepared Foods",
    "rating": 5,
    "reviews": 226,
    "spice": 4,
    "badge": null,
    "badgeClass": "",
    "emoji": "🏺",
    "img": "/images/products/Usiri_Pickle_(amlagooseberry_pickle).jpeg",
    "desc": "Premium Usiri Pickle. Authentic, traditional sun-dried pickle made with carefully selected ingredients and aromatic cold-pressed oils. Perfect companion for your meals."
  }
];
